name: Maven with Spark
description: Combines mvn and spark
inputs:
  title:
    required: true
    description: step title
  script:
    required: true
    description: script to run for step

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: vemonet/setup-spark@v1
      with:
        spark-version: '3.2.1'
        hadoop-version: '3.2'
        scala-version: '2.13'
        spark-url: 'https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2-scala2.13.tgz'
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven #this caches ~/.m2/repo
    - name: ${{ inputs.title }}
      run: ${{ inputs.script }}
      shell: bash
    - name: target
      uses: actions/upload-artifact@v3
      with:
        name: target
        path: target
    - name: testShadesTarget
      uses: actions/upload-artifact@v3
      if: (contains(github.job, 'publish') != true) && (contains(github.job, 'mvn_site') != true) # don't do target when publishing, it's way too large
      with:
        name: shadesTarget
        path: testShades/target