name: Mkdocs
description: Combines mvn and spark

runs:
  using: "composite"
  runs-on: ubuntu-latest
  steps:
    - uses: s-weigand/setup-conda@v1
      with:
        python-version: '3.10'
    - name: setup pips
      run: pip install -r requirements.txt
    - name: setup plant
      run: |
        cp src/build/plantuml .
        chmod +x plantuml
    - name: prep repo for mkdocs / mike
      run: | # borrowed from mhausenblas/mkdocs-deploy-gh-pages/
        export remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

        if ! git config --get user.name; then
            git config --global user.name "${GITHUB_ACTOR}"
        fi

        if ! git config --get user.email; then
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
        fi

        git remote rm origin
        git remote add origin "${remote_repo}"
    - name: prep data for mike # copy mvn site over and version/coverage to expected locations for macros
      run: |
        cp -rf target/site docs/
        cp target/version.txt .
        cp target/coverage.txt .
    - name: run mike
      # needs the path setting here, it's not carried over from setup plant
      run: |
        export ENABLE_PDF_EXPORT=1
        export PATH=$GITHUB_WORKSPACE:$PATH:${pwd}
        echo Asking which plantuml with path $PATH
        which plantuml
        echo Calling mike
        mike deploy --push --update-aliases $(cat version.txt) latest