name: Maven with Spark

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      script:
        required: true
        type: string

jobs:
  setup-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.2.1'
          hadoop-version: '3.2'
          scala-version: '2.13'
          spark-url: 'https://archive.apache.org/dist/spark/spark-3.2.1/spark-3.2.1-bin-hadoop3.2-scala2.13.tgz'
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: ${{ inputs.title }}
        run: ${{ inputs.script }}
      - name: jars
        uses: actions/upload-artifact@v3
        with:
          name: resulting jars
          path: |
            target
            testShades/target
