# Full build setup off main, with ~docsOnly commit filter to run just mvn_site then docs.
name: Default CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_TESTSHADES_OPTS: "-s .m2/settings.xml -f testShades/pom.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # -Dmaven.repo.local=.m2/repository not needed on github, seems ~/.m2 is supported / expected
  MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

jobs:
  # prove tests run with single thread, ensures compilation issues aren't hidden by being run on multiple threads instead of re-used in the same thread (e.g. state resetting etc.)
  verify:
    if: contains(github.event.head_commit.message, '~docsOnly') != true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spark_maven
        with:
          title: Verify
          script: |
            export QUALITY_SPARK_HOSTS=1
            mvn $MAVEN_CLI_OPTS verify -P Spark321

  # all versions that can be built with tests - typically oss only
  testBuilds:
    strategy:
      matrix:
        profile: [Spark3, Spark2, Spark32, Spark321, Spark312, Spark330]
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, '~docsOnly') != true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spark_maven
        with:
          title: Build ${{ matrix.profile }} with tests
          script: |
            mvn $MAVEN_CLI_OPTS clean test install -P ${{ matrix.profile }}
            mvn $MAVEN_CLI_TESTSHADES_OPTS clean install -P ${{ matrix.profile }}

  # all versions that cannot be built with tests - typically Databricks only
  noTestBuilds:
    strategy:
      matrix:
        profile: ["10.4.dbr", "9.1.dbr", "11.3.dbr"]
    runs-on: ubuntu-latest

    if: contains(github.event.head_commit.message, '~docsOnly') != true
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spark_maven
        with:
          title: Build ${{ matrix.profile }} without tests
          script: |
            mvn $MAVEN_CLI_OPTS -DskipTests clean install -P ${{ matrix.profile }}
            mvn $MAVEN_CLI_TESTSHADES_OPTS clean install -P ${{ matrix.profile }}

  mvn_site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: '3.10'
      - uses: ./.github/workflows/spark_maven
        with:
          title: Building site against Spark321
          script: |
            conda install libgomp=11.2.0 # force the right libs
            conda install graphviz=2.50.0 # conda is from fatty

            echo '#!/bin/bash' > dott
            echo 'dot "$@" 2> >(grep -v "pango" | grep -v "Warning" >&2 )' >> dott

            chmod u+x dott

            mvn $MAVEN_CLI_OPTS clean compile org.jacoco:jacoco-maven-plugin:prepare-agent site -P Spark321
            echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -P Spark321) > target/version.txt

            grep -A 3 'Statement coverage:' target/site/scoverage/overview.html | tail -1 | sed 's/[[:space:]]\+//g' > target/coverage.txt
            grep -A 3 'Branch coverage:' target/site/scoverage/overview.html | tail -1 | sed 's/[[:space:]]\+//g' >> target/coverage.txt
      - id: version
        run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -P Spark321) >> "$GITHUB_OUTPUT"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
    outputs:
      version: ${{ steps.version.outputs.version }}

  # only publish snapshots on main by default, or when ~cut-release is in the commits
  publish:
    strategy:
      matrix:
        profile: [Spark3, Spark2, Spark32, Spark321, Spark312, Spark330, "10.4.dbr", "9.1.dbr", "11.3.dbr"]
    needs: [verify, testBuilds, mvn_site, noTestBuilds] # if the builds don't work don't attempt to publish
    if: (contains(github.event.head_commit.message, '~docsOnly') != true) && ( (endsWith(needs.site.outputs.version, '-SNAPSHOT') && github.ref == 'refs/heads/main') || contains(github.event.head_commit.message, '~cut-release') ) # only do snapshots on main by default, releases/snapshots forced with ~cut-release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spark_maven
        with:
          title: Publishing ${{ matrix.profile }}
          script: |
            mvn $MAVEN_CLI_OPTS -DskipTests clean deploy -P ${{ matrix.profile }}
            mvn $MAVEN_CLI_TESTSHADES_OPTS clean deploy -P ${{ matrix.profile }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

  site:
    needs: [mvn_site]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: target
          path: target
      - uses: ./.github/workflows/mkdocs
        with:
          prepScript: |
            cp -rf target/site docs/
            cp target/version.txt .
            cp target/coverage.txt .