# Just runs docs from docs/test, simulates mvn setup
name: Default CI

on:
  push:
    branches: [ "docs/test" ]

env:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  MAVEN_CLI_TESTSHADES_OPTS: "-s .m2/settings.xml -f testShades/pom.xml --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  # -Dmaven.repo.local=.m2/repository not needed on github, seems ~/.m2 is supported / expected
  MAVEN_OPTS: "-Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.class=standard -Dmaven.wagon.http.retryHandler.count=3 -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

jobs:
  site:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spark_maven
        with:
          title: Building site against Spark321
          # bare bones for site setup
          script: |
            echo $(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -P Spark321) > version.txt
            echo 86.30 > coverage.txt
            echo 76.04 >> coverage.txt
      - uses: ./.github/workflows/mkdocs